inherit_mode:
  merge:
    - Exclude

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'test/**/*'
    - 'Gemfile'
    - 'Rakefile'
Lint/Void:
  Enabled: false
Layout/AlignParameters:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Metrics/LineLength:
  Max: 120
